### ISSUE TITLE
API response with members doesn't filter by account

### ISSUE THREAD

**Issue by XaviP** [komunitin/komunitin#155]
Endpoint:
https://demo.integralces.net/ces/api/social/NET1/members?filter[account]=c70f8271-d8e1-4cec-b5c1-a9f6ec3de826

Show all members. Filter doesn't work.

**Comment by estevebadia** [comment]
Done! (Commit d29f24c in ices repo branch 7.x-1.x) and also working in demo.integralces.net (not still in production)
