### ISSUE TITLE
Use Cache to improve UX

### ISSUE THREAD

**Issue by estevebadia** [komunitin/komunitin#176]
- Use in-memory cache when loading lists of resources (done)
 - Use in-memory cache when loading single resources (done)
 - Persist state using localForage (done)
 - Add keys for resource lists so we don't lose nor mix cache when searching or when visiting member lists (done)
  - Update tests.

**Comment by XaviP** [comment]
I don't really know if webassembly fits with an optimization of komunitin, but It's worth taking a look:
https://pablomagaz.com/blog/empezando-con-webassembly
