### ISSUE TITLE
Requesting informations about the project

### ISSUE THREAD

**Issue by Neggia** [komunitin/komunitin#259]
Hello,
we are a group of devs from Italy, we would like to know:
1) Does it support several complementary and alternative currencies?
2) If yes, what logics are there to manage the exchange, emission, deposit/withdrawal of these currencies?
3) Does it have any resilience on various types of attacks (federated network, ...)?
4) Does it support cryptocurencies and non-custodial wallets?
5) What is the license type (GPT3, ...)?

Thanks very much.

**Comment by estevebadia** [comment]
Hi,

Komunitin is an evolution of IntegralCES, a software for alternative/complementary/community currencies that has been working for about 10 years and its main mission it to serve current and future users of this platform. (1) The platform indeed supports many community currencies. One can create a new currency and be the admin of the currency, and then join users to the community. (2) Currencies behave as mutual-credit groups, where the admin can set debit and credit limits for each account. One can "emit" currency by allowing the admin or another special public account to be very negative and send money from this account. The idea for the admin account is that it is managed following some governance scheme within the community that is outside the scope of this software tool. Then, it is also possible to exchange between currencies following previous limit agreements. Each currency has its own fixed (but configurable) exchage rate with the rest. It is even possible to exchange with other platforms like community-exchange.org using a protocol.  Take a look at this API doc https://docs.komunitin.org/accounting/ to check the vision of the intertrading protocol (still not fully implemented). 

(3) No, not this type of cryptocurrency-like architecture. At least not now. When I rewrite the accounting service, will be the moment of checking that. For example, the accounting service could be an API layer in front of a smart contract on an ETH-like network. But it does not need to be like that, I'm not against classical databases. It will need to be evaluated weighting all pros and cons. (4) also not now, but I'd not be against that. Note that while I really like (and understand some of) the crypto descentralized architecture, the politics behind this software are not the same as the politics behind most cryptos. Here is not the individual who really owns their coins, but the local network by the admin account. It is meant to be a tool for local communities.

Currently this repo has the front-end PWA application. The backend is done in integralces, so currently users can use both the old interface and the new alpha komunitin app. The idea is that when the UI is done, the next step will be moving the backend from IntegralCES (this is a set of drupal modules) to several new services. Mainly one for accounting and one for offers, needs and social features. 

I've not really thought about the license, but it should be something like GPL3 or AGPL. I can add the license file if that allows anyone to contribute. I'm contributing to this project on my spare time, so I'm not always available for answers or reviews.

**Comment by Neggia** [comment]
Hello again, this sounds very interesting and close to what we need! I myself am a Bitcoin sCrypt developer (https://scrypt.io/) and my idea was to add the blockchain layer with BSV-20 tokenization (https://docs.1satordinals.com/bsv20) of currencies and smartcontracts as a further step, similar to your ETH one.
We would like to dig in more, can you give us your availability for an online meeting?
Cheers.

**Comment by estevebadia** [comment]
You may reach me at komunitinbox@gmail.com
