### ISSUE TITLE
make Group and GroupStats cards clickable

### ISSUE THREAD

**Issue by estevebadia** [komunitin/komunitin#47]
See material.io spec. Cards section

**Comment by XaviP** [comment]
- Make GroupCard clickable: this is the way I've found to link avatar, title and subtitle in card
https://github.com/komunitin/komunitin/commit/a4e67435a3d330367bf4c64876336a26adec2717
- I don't understand what you mean by making GroupStats clickable.

**Comment by estevebadia** [comment]
Which problems do you have making the whole card clicable?

**Comment by estevebadia** [comment]
I found this issue: https://github.com/quasarframework/quasar/issues/6450 and, within it, this snippet https://codepen.io/smolinari/pen/ExjNPGv on how you could do it.

Perhaps it doesn't apply to our case for some resason tough...

**Comment by XaviP** [comment]
Hi, if I make the entire card clickable with:
`<q-card v-if="group" tabindex="0">`
`  <div v-ripple @click="goToGroup(group.attributes.code)" class="cursor-pointer relative-position">`
there are problems with share button, map controls and action buttons. They don't work as expected, the click send to the card page.
![captura](https://user-images.githubusercontent.com/6750293/79875718-53383580-83ea-11ea-8b28-0b4332894675.png)

**Comment by estevebadia** [comment]
Aquesta implementació de posar el handler a varis elements no m'agrada gaire la veritat. Sino trobem res millor igual casi prefereixo deixar-ho com està: és massa d'hora per fer invents encara ;)

El tema és que el div hauria d'estar per sota dels botons (z-index, tot i que no proposo tocar el z-index per CSS). Hi ha algun inconvenient en posar els atributs a l'element `q-card` ? Potser llavors el mapa es queda l'event (igual no seria tan greu això)? Una altra seria solucionar-ho amb una `directive` nostra i almenys tenim el possible apanyo localitzat.

**Comment by estevebadia** [comment]
Amb lo de `directive` vull dir fer un mini-plugin de manera que a "qualsevol" element puguéssis posar-li algo tipus:
```
<q-card v-clickable-to:"/route/address">
```
I que faci tota la feina que convingui: posar el ripple i el click handler a(ls) l'element(s) que interessi. Això aniria a `src/plugins`.

**Comment by estevebadia** [comment]
Però la meva idea era que això era algo fàcil que podia servir per començar a entrar en el Vue i tal. Si no és així podem descartar l'issue directament, que la funcionalitat que dóna tampoc és important a hores d'ara.

**Comment by XaviP** [comment]
In https://github.com/komunitin/komunitin/commit/3e1a786b0722f3e23c71a3fc093cb667831d5ddc
- group description clickable
- offers, needs, members and currency cards clickable in GroupStats

**Comment by XaviP** [comment]
Ok, faig PR i deixo la issue per advanced devs :-)

**Comment by estevebadia** [comment]
Done!
