### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by edumag** [komunitin/komunitin#8]
https://vuepress.vuejs.org                                                      
                                                                                
```                                                                             
npm install -g @vuese/cli                                                       
vuese gen                                                                       
```                                                                             
                                                                                
Lanzar servidor de vuese.                                                       
                                                                                
```                                                                             
vuese serve --open                                                              
```

**Comment by edumag** [comment]
Documentación de código
=======================

Busco que es lo que se está utilizando con vuejs.

Cuesta encontrar un generador de código que se combine bien con
typescript y vue.

De todo lo que he probado me quedo con typedoc que cubrirá lo más
importante y entiendo que en algún momento ya se podrá adaptar a los
componentes de vue.


### vuese

<https://vuepress.vuejs.org>

`` ` npm install -g @vuese/cli vuese gen ``\`

Lanzar servidor de vuese.

`` ` vuese serve --open ``\`

### typedoc

Al pasar typescript utilizamos typedoc.

`` ` npm install --global typedoc ``\`

Añadido script a packiage.json: :

    "doc": "typedoc --out docs src"

Ahora podemos generar la documentación con "npm run doc".

Ignoro carpeta de documentación desde git.

Tiene buena pinta pero no muestra ningún resultado por no trabajar con
ficheros vue.

Añadimos plugin de typedoc: :

    npm i -D typedoc-webpack-plugin typedoc

No consigo que funcione con los ficheros .vue

Referencias:

-   <https://typedoc.org>

### yuidocjs

Instalar: :

    npm -g install yuidocjs

Ejecutar: :

    yuidoc -o docs -e '.ts', '.js', '.vue' --server `find ./src -type d`

Parece que se concentra en clases y módulos con lo cual no muestra nada
de los componentes.

### Better-docs

<https://github.com/SoftwareBrothers/better-docs>

Vídeo: <https://www.youtube.com/watch?v=UBMYogTzsBk>

Instalación: :

    npm install -g --save-dev jsdocs
    npm install -g --save-dev better-docs
    npm install -g --save-dev parcel-bundler
    npm install --save-dev jsdoc-vuejs

jsdoc.json: :

    {
        "tags": {
            "allowUnknownTags": ["component"]
        },
        "source": {
            "include": ["./src"],
            "includePattern": ".(jsx|js|ts|tsx)$",
            "excludePattern": "(node_modules/|docs)"
        },
        "plugins": [
            "plugins/markdown",
            "jsdoc-mermaid",
            "node_modules/better-docs/component",
            "node_modules/jsdoc-vuejs"
        ],
        "opts": {
            "encoding": "utf8",
            "destination": "docs/",
            "readme": "README.md",
            "recurse": true,
            "template": "node_modules/better-docs",
            "verbose": true
        },
        "templates": {
            "cleverLinks": false,
            "monospaceLinks": false,
            "better-docs": {
                "name": "Komunitin",
                "logo": "src/assets/komunitin-logo.svg",
                // "trackingCode": "tracking-code-which-will-go-to-the-HEAD",
            "hideGenerator": false,
                "navigation": [
                    {
                        "label": "Github",
                        "href": "https://github.com/komunitin/komunitin"
                    },
                    {
                        "label": "Documentation",
                        "href": "https://github.com/komunitin/komunitin"
                    }
                ]
            }
        }
    }

Tampoco funciona con los componentes de vue.

### documentation

<https://github.com/documentationjs/documentation/blob/master/docs/GETTING_STARTED.md>

Instalación: :

    npm install -g documentation

Ejecutar: :

    documentation build src/** -f html -o docs

No esta mal pero no coge los ficheros de typescript.

**Comment by estevebadia** [comment]
He visto también esto: https://vue-styleguidist.github.io/
Parece que sirve para documentar componentes vue, con soporte para typescript y class-type components e integrable con vuepress.

Demos: https://vue-styleguidist.github.io/Examples.html

**Comment by edumag** [comment]
Styleguidist
============

<https://vue-styleguidist.github.io/docs/GettingStarted.html>

Errores al instalar: :

    npm install --save-dev vue-styleguidist
    npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0> for migration path(s).
    npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
    + vue-styleguidist@4.7.6

Parece que no se lleva bien con quasar.
